import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='border-b border-black shadow-[0px_10px_20px_0px_rgba(0,0,0,0.7),0px_15px_30px_10px_rgba(10,10,10,0.7)]  w-full fixed backdrop-blur-sm bg-slate-900/95 z-10 h-10'></div>
        <div className='border-t  border-black  bottom-0 backdrop-blur-sm bg-slate-900/90 w-full fixed h-10 z-10'></div>
        {children}
        
        </body>
    </html>
  )
}
